export const ROUTES = {
	home: ':lang?/',
	aboutUs: ':lang?/about-us',
	shipment: ':lang?/shipment',
	payment: ':lang?/payment',
	contacts: ':lang?/contacts',
	guaranteeAndRefund: ':lang?/guarantee-and-refund',
	publicOffer: ':lang?/public-offer',
	catalog: ':lang?/catalog/:section',
	bookmarks: ':lang?/bookmarks/',
	comparison: ':lang?/comparison/',
	cart: ':lang?/cart/',
	order: ':lang?/order/',
	tyreDiskSizeCalc: ':lang?/tyre-disk-size-calc/',
};
